# Generated by Django 3.0.2 on 2020-05-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laptop', '0002_auto_20200514_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
